# Generated by Django 4.2.6 on 2023-10-09 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='key_for_employee',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='key_for_responsable',
        ),
    ]
