# Generated by Django 4.1.3 on 2023-10-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamation', '0003_alter_reclamation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='Titre',
            field=models.CharField(max_length=50),
        ),
    ]
